version: 0.2
phases:
    install:
        commands:
            - echo print env variables 
            - sudo yum install -y yum-utils
            - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
            - sudo yum -y install terraform
            - terraform -help
    pre_build:
        commands:
           - echo pre_build stage on `date`
           - echo --- checking AWS creds ---
#           - aws s3 ls
    build:
        commands:
            - echo build stage on `date`
            - echo ---- listing all the files ----
            - pwd
            - ls 
            - echo --- terraform init ---
            - terraform init
            - echo terraform plan
            - terraform plan
            - echo --- terraform apply work --- 
            - terraform apply --auto-approve
    post_build:
        commands:
            echo post_build stage on `date`